version: '3.8'

services:
  database:
    container_name: pg-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: delivero
      PGDATA: /data/postgres
    volumes:
      -  ./data/pg:/data/postgres
    networks:
      - backend

  backend:
    container_name: nestjs_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 3333:3333
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:docker@database:5432/delivero?schema=public
    networks:
      - backend
      - frontend

  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL: http://backend:3333
    ports:
      - 80:80
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
